// Mocks generated by Mockito 5.0.16 from annotations
// in hdrezka_client/test/features/film/usecases/get_film_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:hdrezka_client/core/error/failure.dart' as _i5;
import 'package:hdrezka_client/features/film/domain/entities/film.dart' as _i6;
import 'package:hdrezka_client/features/film/domain/repository/film_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [FilmRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilmRepository extends _i1.Mock implements _i3.FilmRepository {
  MockFilmRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Film>> getFilm(int? search_request_id, String? url, String? type) =>
      (super.noSuchMethod(Invocation.method(#getFilm, [url]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.Film>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Film>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Film>>);
  @override
  String toString() => super.toString();
}
